// CoinGecko asset URLs — stable and covers all major/emerging coins
const COINGECKO = "https://assets.coingecko.com/coins/images";

export const COIN_ICONS: Record<string, string> = {
  BTC:  `${COINGECKO}/1/small/bitcoin.png`,
  ETH:  `${COINGECKO}/279/small/ethereum.png`,
  USDT: `${COINGECKO}/325/small/Tether.png`,
  BNB:  `${COINGECKO}/825/small/binance-coin-logo.png`,
  SOL:  `${COINGECKO}/4128/small/solana.png`,
  USDC: `${COINGECKO}/6319/small/USD_Coin_icon.png`,
  XRP:  `${COINGECKO}/44/small/xrp-symbol-white-128.png`,
  DOGE: `${COINGECKO}/5/small/dogecoin.png`,
  TRX:  `${COINGECKO}/1094/small/tron-logo.png`,
  ADA:  `${COINGECKO}/975/small/cardano.png`,
  AVAX: `${COINGECKO}/12559/small/Avalanche_Circle_RedWhite_Trans.png`,
  SHIB: `${COINGECKO}/11939/small/shiba.png`,
  DOT:  `${COINGECKO}/12171/small/polkadot.png`,
  LINK: `${COINGECKO}/877/small/chainlink-new-logo.png`,
  LTC:  `${COINGECKO}/2/small/litecoin.png`,
  NEAR: `${COINGECKO}/10365/small/near.jpg`,
  UNI:  `${COINGECKO}/12504/small/uniswap-uni.png`,
  MATIC:`${COINGECKO}/4713/small/matic-token-icon.png`,
  ATOM: `${COINGECKO}/1481/small/cosmos_hub.png`,
  ETC:  `${COINGECKO}/453/small/ethereum-classic-logo.png`,
  XLM:  `${COINGECKO}/100/small/Stellar_symbol_black_RGB.png`,
  XMR:  `${COINGECKO}/69/small/monero_logo.png`,
  HBAR: `${COINGECKO}/3688/small/hbar.png`,
  OP:   `${COINGECKO}/25244/small/Optimism.png`,
  FIL:  `${COINGECKO}/12817/small/filecoin.png`,
  ARB:  `${COINGECKO}/16547/small/photo_2023-03-29_21.47.00.jpeg`,
  APT:  `${COINGECKO}/26455/small/aptos_round.png`,
  VET:  `${COINGECKO}/1167/small/VET_Token_Icon.png`,
  INJ:  `${COINGECKO}/12882/small/Secondary_Symbol.png`,
  RNDR: `${COINGECKO}/11636/small/rndr.png`,
  PEPE: `${COINGECKO}/29850/small/pepe-token.jpeg`,
  KAS:  `${COINGECKO}/25751/small/kaspa-icon-exchanges.png`,
  SUI:  `${COINGECKO}/26375/small/sui_asset.jpeg`,
  STRK: `${COINGECKO}/26433/small/starknet.png`,
  W:    `${COINGECKO}/35087/small/womrhole_logo_full_color_rgb_2000px_72ppi_fb766ac85a.png`,
};
