/** Maps CoinGecko coin ID → Binance trading pair symbol */
export const BINANCE_SYMBOLS: Record<string, string> = {
  bitcoin:             "BTCUSDT",
  ethereum:            "ETHUSDT",
  solana:              "SOLUSDT",
  binancecoin:         "BNBUSDT",
  ripple:              "XRPUSDT",
  dogecoin:            "DOGEUSDT",
  cardano:             "ADAUSDT",
  "avalanche-2":       "AVAXUSDT",
  chainlink:           "LINKUSDT",
  polkadot:            "DOTUSDT",
  litecoin:            "LTCUSDT",
  uniswap:             "UNIUSDT",
  "matic-network":     "MATICUSDT",
  cosmos:              "ATOMUSDT",
  "ethereum-classic":  "ETCUSDT",
  stellar:             "XLMUSDT",
  monero:              "XMRUSDT",
  "hedera-hashgraph":  "HBARUSDT",
  optimism:            "OPUSDT",
  filecoin:            "FILUSDT",
  arbitrum:            "ARBUSDT",
  aptos:               "APTUSDT",
  vechain:             "VETUSDT",
  near:                "NEARUSDT",
  "shiba-inu":         "SHIBUSDT",
  "injective-protocol":"INJUSDT",
  "render-token":      "RENDERUSDT",
  sui:                 "SUIUSDT",
  kaspa:               "KASUSDT",
  pepe:                "PEPEUSDT",
  tron:                "TRXUSDT",
};

/** Maps CoinDetailView timeframe label → Binance kline interval */
export const TF_TO_INTERVAL: Record<string, { interval: string; limit: number }> = {
  "1D":  { interval: "15m", limit: 96  },
  "1W":  { interval: "1h",  limit: 168 },
  "1M":  { interval: "4h",  limit: 180 },
  "3M":  { interval: "1d",  limit: 90  },
  "1Y":  { interval: "1d",  limit: 365 },
  "ALL": { interval: "1w",  limit: 260 },
};
