/** Maps coin symbol → CoinGecko coin ID used in /coins/[id] route */
export const COIN_IDS: Record<string, string> = {
  BTC:   "bitcoin",
  ETH:   "ethereum",
  USDT:  "tether",
  BNB:   "binancecoin",
  SOL:   "solana",
  USDC:  "usd-coin",
  XRP:   "ripple",
  DOGE:  "dogecoin",
  TRX:   "tron",
  ADA:   "cardano",
  AVAX:  "avalanche-2",
  SHIB:  "shiba-inu",
  DOT:   "polkadot",
  LINK:  "chainlink",
  LTC:   "litecoin",
  NEAR:  "near",
  UNI:   "uniswap",
  MATIC: "matic-network",
  ATOM:  "cosmos",
  ETC:   "ethereum-classic",
  XLM:   "stellar",
  XMR:   "monero",
  HBAR:  "hedera-hashgraph",
  OP:    "optimism",
  FIL:   "filecoin",
  ARB:   "arbitrum",
  APT:   "aptos",
  VET:   "vechain",
  INJ:   "injective-protocol",
  RNDR:  "render-token",
  PEPE:  "pepe",
  KAS:   "kaspa",
  SUI:   "sui",
};
